var VOCAB={
greetings:[
{l:'Jambo',e:'Hello',p:'jam-boh',ic:'👋'},
{l:'Hujambo',e:'Hello (to one person)',p:'hoo-jam-boh',ic:'😊'},
{l:'Hamjambo',e:'Hello (to many)',p:'ham-jam-boh',ic:'👥'},
{l:'Sijambo',e:'I am fine',p:'see-jam-boh',ic:'😊'},
{l:'Habari',e:'News / How are you?',p:'hah-bah-ree',ic:'🙋'},
{l:'Nzuri',e:'Good / Fine',p:'n-zoo-ree',ic:'✨'},
{l:'Asante',e:'Thank you',p:'ah-sahn-teh',ic:'🙏'},
{l:'Asante sana',e:'Thank you very much',p:'ah-sahn-teh sah-nah',ic:'🙏'},
{l:'Karibu',e:'Welcome / You are welcome',p:'kah-ree-boo',ic:'🤗'},
{l:'Tafadhali',e:'Please',p:'tah-fah-dah-lee',ic:'🤲'},
{l:'Samahani',e:'Sorry / Excuse me',p:'sah-mah-hah-nee',ic:'😔'},
{l:'Ndiyo',e:'Yes',p:'n-dee-yoh',ic:'✅'},
{l:'Hapana',e:'No',p:'hah-pah-nah',ic:'🚫'},
{l:'Sawa',e:'Okay / Alright',p:'sah-wah',ic:'👍'},
{l:'Sawa sawa',e:'All good / No problem',p:'sah-wah sah-wah',ic:'👌'},
{l:'Kwaheri',e:'Goodbye',p:'kwah-heh-ree',ic:'👋'},
{l:'Kwa heri ya kuonana',e:'Goodbye until we meet again',p:'kwah heh-ree yah kwoh-nah-nah',ic:'👋'},
{l:'Habari ya asubuhi',e:'Good morning',p:'hah-bah-ree yah ah-soo-boo-hee',ic:'🌅'},
{l:'Habari ya mchana',e:'Good afternoon',p:'hah-bah-ree yah m-chah-nah',ic:'☀️'},
{l:'Habari ya jioni',e:'Good evening',p:'hah-bah-ree yah jee-oh-nee',ic:'🌆'},
{l:'Lala salama',e:'Good night / Sleep well',p:'lah-lah sah-lah-mah',ic:'🌙'},
{l:'Nakupenda',e:'I love you',p:'nah-koo-pehn-dah',ic:'❤️'},
{l:'Pole',e:'Sorry / Condolences',p:'poh-leh',ic:'💛'},
{l:'Pole pole',e:'Slowly / Take it easy',p:'poh-leh poh-leh',ic:'🐢'},
{l:'Haraka',e:'Quickly / Hurry',p:'hah-rah-kah',ic:'⚡'},
{l:'Jina lako nani',e:'What is your name?',p:'jee-nah lah-koh nah-nee',ic:'🪪'},
{l:'Jina langu ni',e:'My name is',p:'jee-nah lahn-goo nee',ic:'🪪'},
{l:'Unatoka wapi',e:'Where are you from?',p:'oo-nah-toh-kah wah-pee',ic:'🌍'},
{l:'Sijui',e:'I don\'t know',p:'see-joo-ee',ic:'🤷'},
{l:'Naelewa',e:'I understand',p:'nah-eh-leh-wah',ic:'💡'},
{l:'Tena',e:'Again / Also',p:'teh-nah',ic:'🔄'},
{l:'Safi',e:'Clean / Great / Cool',p:'sah-fee',ic:'✨'},
{l:'Mambo',e:'Things / What\'s up?',p:'mahm-boh',ic:'😎'},
{l:'Poa',e:'Cool / Fine (slang)',p:'poh-ah',ic:'😎'},
{l:'Hakuna matata',e:'No worries / No problem',p:'hah-koo-nah mah-tah-tah',ic:'🌟'},
{l:'Mungu akubariki',e:'God bless you',p:'moon-goo ah-koo-bah-ree-kee',ic:'🙏'},
{l:'Salama',e:'Safe / Peace',p:'sah-lah-mah',ic:'🕊️'},
{l:'Karibu tena',e:'Welcome again',p:'kah-ree-boo teh-nah',ic:'🤗'},
{l:'Tutaonana',e:'We will meet again',p:'too-tah-oh-nah-nah',ic:'👋'}
],
people:[
{l:'Mama',e:'Mother',p:'mah-mah',ic:'👩'},
{l:'Baba',e:'Father',p:'bah-bah',ic:'👨'},
{l:'Mtoto',e:'Child',p:'m-toh-toh',ic:'👶'},
{l:'Watoto',e:'Children',p:'wah-toh-toh',ic:'👧'},
{l:'Mke',e:'Wife',p:'m-keh',ic:'👰'},
{l:'Mume',e:'Husband',p:'moo-meh',ic:'🧔'},
{l:'Kaka',e:'Brother / Older male',p:'kah-kah',ic:'👦'},
{l:'Dada',e:'Sister / Older female',p:'dah-dah',ic:'👧'},
{l:'Babu',e:'Grandfather',p:'bah-boo',ic:'👴'},
{l:'Bibi',e:'Grandmother / Mrs',p:'bee-bee',ic:'👵'},
{l:'Shangazi',e:'Aunt (paternal)',p:'shahn-gah-zee',ic:'👩'},
{l:'Mjomba',e:'Uncle (maternal)',p:'m-johm-bah',ic:'👨'},
{l:'Mtu',e:'Person',p:'m-too',ic:'🧑'},
{l:'Watu',e:'People',p:'wah-too',ic:'👥'},
{l:'Rafiki',e:'Friend',p:'rah-fee-kee',ic:'🤗'},
{l:'Mwalimu',e:'Teacher',p:'mwah-lee-moo',ic:'👩‍🏫'},
{l:'Daktari',e:'Doctor',p:'dah-ktah-ree',ic:'👨‍⚕️'},
{l:'Mwanamke',e:'Woman',p:'mwah-nahm-keh',ic:'👩'},
{l:'Mwanaume',e:'Man',p:'mwah-nah-oo-meh',ic:'👨'},
{l:'Msichana',e:'Girl',p:'m-see-chah-nah',ic:'👧'},
{l:'Mvulana',e:'Boy',p:'m-voo-lah-nah',ic:'👦'},
{l:'Mzee',e:'Elder / Old person',p:'m-zeh-eh',ic:'🧓'},
{l:'Mkulima',e:'Farmer',p:'m-koo-lee-mah',ic:'👨‍🌾'},
{l:'Dereva',e:'Driver',p:'deh-reh-vah',ic:'🚗'},
{l:'Mfanyakazi',e:'Worker / Employee',p:'m-fah-nyah-kah-zee',ic:'👷'},
{l:'Jirani',e:'Neighbor',p:'jee-rah-nee',ic:'🏘️'},
{l:'Mgonjwa',e:'Sick person / Patient',p:'m-gohn-jwah',ic:'🤒'},
{l:'Mgeni',e:'Guest / Stranger',p:'m-geh-nee',ic:'🧳'},
{l:'Mwana',e:'Son / Daughter',p:'mwah-nah',ic:'🧑'},
{l:'Wazazi',e:'Parents',p:'wah-zah-zee',ic:'👨‍👩‍👧'},
{l:'Familia',e:'Family',p:'fah-mee-lee-yah',ic:'👨‍👩‍👧‍👦'},
{l:'Mpenzi',e:'Loved one / Dear',p:'m-pehn-zee',ic:'❤️'},
{l:'Kiongozi',e:'Leader',p:'kee-ohn-goh-zee',ic:'👑'},
{l:'Mtawala',e:'Ruler / Governor',p:'m-tah-wah-lah',ic:'👑'},
{l:'Polisi',e:'Police officer',p:'poh-lee-see',ic:'👮'},
{l:'Mwimbaji',e:'Singer',p:'mweem-bah-jee',ic:'🎤'},
{l:'Mpishi',e:'Cook / Chef',p:'m-pee-shee',ic:'👨‍🍳'},
{l:'Mhusika',e:'Character / Actor',p:'m-hoo-see-kah',ic:'🎭'},
{l:'Ndugu',e:'Brother / Comrade',p:'n-doo-goo',ic:'🤝'}
],
body:[
{l:'Kichwa',e:'Head',p:'kee-chwah',ic:'🗣️'},
{l:'Macho',e:'Eyes',p:'mah-choh',ic:'👁️'},
{l:'Sikio',e:'Ear',p:'see-kee-oh',ic:'👂'},
{l:'Pua',e:'Nose',p:'poo-ah',ic:'👃'},
{l:'Mdomo',e:'Mouth',p:'m-doh-moh',ic:'👄'},
{l:'Meno',e:'Teeth',p:'meh-noh',ic:'🦷'},
{l:'Mkono',e:'Hand / Arm',p:'m-koh-noh',ic:'🖐️'},
{l:'Mguu',e:'Leg / Foot',p:'m-goo',ic:'🦵'},
{l:'Tumbo',e:'Stomach',p:'toom-boh',ic:'🫃'},
{l:'Moyo',e:'Heart',p:'moh-yoh',ic:'❤️'},
{l:'Ngozi',e:'Skin',p:'n-goh-zee',ic:'🧴'},
{l:'Nywele',e:'Hair',p:'n-yeh-leh',ic:'💇'},
{l:'Afya',e:'Health',p:'ah-fyah',ic:'🌱'},
{l:'Ugonjwa',e:'Illness / Disease',p:'oo-gohn-jwah',ic:'🤒'},
{l:'Miguu',e:'Legs',p:'mee-goo',ic:'🦶'},
{l:'Mikono',e:'Hands',p:'mee-koh-noh',ic:'🙌'},
{l:'Mgongo',e:'Back',p:'m-gohn-goh',ic:'🫁'},
{l:'Nguvu',e:'Strength',p:'n-goo-voo',ic:'💪'},
{l:'Bega',e:'Shoulder',p:'beh-gah',ic:'💪'},
{l:'Damu',e:'Blood',p:'dah-moo',ic:'🩸'},
{l:'Maumivu',e:'Pain',p:'mah-oo-mee-voo',ic:'😣'},
{l:'Ulimi',e:'Tongue',p:'oo-lee-mee',ic:'👅'},
{l:'Vidole',e:'Fingers / Toes',p:'vee-doh-leh',ic:'🖐️'},
{l:'Kifua',e:'Chest',p:'kee-foo-ah',ic:'🫁'},
{l:'Shingo',e:'Neck',p:'sheen-goh',ic:'🦒'},
{l:'Masikio',e:'Ears (plural)',p:'mah-see-kee-oh',ic:'👂'},
{l:'Goti',e:'Knee',p:'goh-tee',ic:'🦵'},
{l:'Dawa',e:'Medicine',p:'dah-wah',ic:'💊'},
{l:'Pumzi',e:'Breath',p:'poom-zee',ic:'💨'},
{l:'Roho',e:'Soul / Spirit',p:'roh-hoh',ic:'✨'},
{l:'Uhai',e:'Life / Existence',p:'oo-hah-ee',ic:'🌱'},
{l:'Homa',e:'Fever',p:'hoh-mah',ic:'🤒'},
{l:'Jeraha',e:'Wound / Injury',p:'jeh-rah-hah',ic:'🩹'},
{l:'Hospitali',e:'Hospital',p:'hoh-spee-tah-lee',ic:'🏥'},
{l:'Chungu',e:'Painful / Difficult',p:'choon-goo',ic:'😣'},
{l:'Pumzika',e:'Rest',p:'poom-zee-kah',ic:'😴'},
{l:'Fahamu',e:'Consciousness / Sense',p:'fah-hah-moo',ic:'🧠'},
{l:'Mwili',e:'Body',p:'mwee-lee',ic:'🧍'},
{l:'Uso',e:'Face',p:'oo-soh',ic:'😊'}
],
food:[
{l:'Chakula',e:'Food',p:'chah-koo-lah',ic:'🍽️'},
{l:'Maji',e:'Water',p:'mah-jee',ic:'💧'},
{l:'Mboga',e:'Vegetables',p:'m-boh-gah',ic:'🥦'},
{l:'Nyama',e:'Meat',p:'n-yah-mah',ic:'🥩'},
{l:'Maziwa',e:'Milk',p:'mah-zee-wah',ic:'🥛'},
{l:'Mkate',e:'Bread',p:'m-kah-teh',ic:'🍞'},
{l:'Ndizi',e:'Banana',p:'n-dee-zee',ic:'🍌'},
{l:'Nyanya',e:'Tomato',p:'n-yah-nyah',ic:'🍅'},
{l:'Chumvi',e:'Salt',p:'choom-vee',ic:'🧂'},
{l:'Mafuta',e:'Oil / Fat',p:'mah-foo-tah',ic:'🫙'},
{l:'Karanga',e:'Peanuts / Groundnuts',p:'kah-rahn-gah',ic:'🥜'},
{l:'Ugali',e:'Maize porridge (staple)',p:'oo-gah-lee',ic:'🥣'},
{l:'Sukari',e:'Sugar',p:'soo-kah-ree',ic:'🍬'},
{l:'Kahawa',e:'Coffee',p:'kah-hah-wah',ic:'☕'},
{l:'Chai',e:'Tea',p:'chah-ee',ic:'🫖'},
{l:'Chungwa',e:'Orange',p:'choon-gwah',ic:'🍊'},
{l:'Embe',e:'Mango',p:'ehm-beh',ic:'🥭'},
{l:'Mayai',e:'Eggs',p:'mah-yah-ee',ic:'🥚'},
{l:'Kuku',e:'Chicken',p:'koo-koo',ic:'🐔'},
{l:'Njaa',e:'Hunger',p:'n-jah',ic:'😫'},
{l:'Mahindi',e:'Maize / Corn',p:'mah-heen-dee',ic:'🌽'},
{l:'Maharage',e:'Beans',p:'mah-hah-rah-geh',ic:'🫘'},
{l:'Samaki',e:'Fish',p:'sah-mah-kee',ic:'🐟'},
{l:'Pilipili',e:'Pepper / Chilli',p:'pee-lee-pee-lee',ic:'🌶️'},
{l:'Wali',e:'Cooked rice',p:'wah-lee',ic:'🍚'},
{l:'Mchuzi',e:'Sauce / Curry / Stew',p:'m-choo-zee',ic:'🍲'},
{l:'Chapati',e:'Flatbread',p:'chah-pah-tee',ic:'🫓'},
{l:'Mandazi',e:'Fried dough / Doughnut',p:'mahn-dah-zee',ic:'🍩'},
{l:'Pombe',e:'Local beer / Alcohol',p:'pohm-beh',ic:'🍺'},
{l:'Matunda',e:'Fruits',p:'mah-toon-dah',ic:'🍎'},
{l:'Viazi',e:'Potatoes',p:'vee-ah-zee',ic:'🥔'},
{l:'Pilau',e:'Spiced rice dish',p:'pee-lah-oo',ic:'🍛'},
{l:'Biryani',e:'Biryani rice',p:'beer-yah-nee',ic:'🍛'},
{l:'Maharagwe',e:'Red kidney beans',p:'mah-hah-rah-gweh',ic:'🫘'},
{l:'Soksi',e:'Juice',p:'soh-ksee',ic:'🥤'},
{l:'Kula',e:'To eat',p:'koo-lah',ic:'😋'},
{l:'Kunywa',e:'To drink',p:'koon-ywah',ic:'🥤'},
{l:'Kupika',e:'To cook',p:'koo-pee-kah',ic:'🍳'},
{l:'Tamu',e:'Sweet / Delicious',p:'tah-moo',ic:'😋'}
],
home:[
{l:'Nyumba',e:'House / Home',p:'n-yoom-bah',ic:'🏠'},
{l:'Chumba',e:'Room',p:'choom-bah',ic:'🚪'},
{l:'Mlango',e:'Door',p:'m-lahn-goh',ic:'🚪'},
{l:'Sebule',e:'Living room',p:'seh-boo-leh',ic:'🛋️'},
{l:'Kitanda',e:'Bed',p:'kee-tahn-dah',ic:'🛏️'},
{l:'Kiti',e:'Chair',p:'kee-tee',ic:'🪑'},
{l:'Meza',e:'Table',p:'meh-zah',ic:'🪞'},
{l:'Kitabu',e:'Book',p:'kee-tah-boo',ic:'📖'},
{l:'Simu',e:'Phone',p:'see-moo',ic:'📱'},
{l:'Umeme',e:'Electricity',p:'oo-meh-meh',ic:'⚡'},
{l:'Nguo',e:'Clothes',p:'n-goo-oh',ic:'👕'},
{l:'Viatu',e:'Shoes',p:'vee-ah-too',ic:'👟'},
{l:'Mfuko',e:'Bag / Pocket',p:'m-foo-koh',ic:'👜'},
{l:'Kisu',e:'Knife',p:'kee-soo',ic:'🔪'},
{l:'Ufunguo',e:'Key',p:'oo-foon-goo-oh',ic:'🔑'},
{l:'Moto',e:'Fire',p:'moh-toh',ic:'🔥'},
{l:'Taa',e:'Lamp / Light',p:'tah',ic:'💡'},
{l:'Fagio',e:'Broom',p:'fah-gee-oh',ic:'🧹'},
{l:'Zana',e:'Tool / Equipment',p:'zah-nah',ic:'🔧'},
{l:'Karatasi',e:'Paper / Document',p:'kah-rah-tah-see',ic:'📄'},
{l:'Kikapu',e:'Basket',p:'kee-kah-poo',ic:'🧺'},
{l:'Kitambaa',e:'Cloth / Fabric',p:'kee-tahm-bah',ic:'🧣'},
{l:'Mpira',e:'Ball / Rubber',p:'m-pee-rah',ic:'⚽'},
{l:'Jiko',e:'Stove / Charcoal stove',p:'jee-koh',ic:'🍳'},
{l:'Sufuria',e:'Cooking pot',p:'soo-foo-ree-yah',ic:'🍲'},
{l:'Bakuli',e:'Bowl',p:'bah-koo-lee',ic:'🥣'},
{l:'Sahani',e:'Plate / Dish',p:'sah-hah-nee',ic:'🍽️'},
{l:'Kikombe',e:'Cup',p:'kee-kohm-beh',ic:'☕'},
{l:'Bafu',e:'Bathroom',p:'bah-foo',ic:'🚿'},
{l:'Choo',e:'Toilet',p:'choh',ic:'🚽'},
{l:'Bustani',e:'Garden',p:'boos-tah-nee',ic:'🌿'},
{l:'Ukuta',e:'Wall',p:'oo-koo-tah',ic:'🏗️'},
{l:'Dari',e:'Balcony / Porch',p:'dah-ree',ic:'🏡'},
{l:'Paa',e:'Roof',p:'pah',ic:'🏠'},
{l:'Dirisha',e:'Window',p:'dee-ree-shah',ic:'🪟'},
{l:'Jokofu',e:'Fridge / Refrigerator',p:'joh-koh-foo',ic:'🧊'},
{l:'Godoro',e:'Mattress',p:'goh-doh-roh',ic:'🛏️'},
{l:'Mto',e:'Pillow',p:'m-toh',ic:'😴'},
{l:'Blanketi',e:'Blanket',p:'blahn-keh-tee',ic:'🛏️'}
],
nature:[
{l:'Mti',e:'Tree',p:'m-tee',ic:'🌳'},
{l:'Msitu',e:'Forest / Jungle',p:'m-see-too',ic:'🌲'},
{l:'Tembo',e:'Elephant',p:'tehm-boh',ic:'🐘'},
{l:'Simba',e:'Lion',p:'seem-bah',ic:'🦁'},
{l:'Nyani',e:'Monkey / Baboon',p:'n-yah-nee',ic:'🐒'},
{l:'Kuku',e:'Chicken / Hen',p:'koo-koo',ic:'🐔'},
{l:'Mbwa',e:'Dog',p:'m-bwah',ic:'🐕'},
{l:'Ng\'ombe',e:'Cow',p:'n-gohm-beh',ic:'🐄'},
{l:'Paka',e:'Cat',p:'pah-kah',ic:'🐈'},
{l:'Ndege',e:'Bird',p:'n-deh-geh',ic:'🐦'},
{l:'Ziwa',e:'Lake',p:'zee-wah',ic:'🌊'},
{l:'Mbuzi',e:'Goat',p:'m-boo-zee',ic:'🐐'},
{l:'Kondoo',e:'Sheep',p:'kohn-doh',ic:'🐑'},
{l:'Mvua',e:'Rain',p:'m-voo-ah',ic:'🌧️'},
{l:'Upepo',e:'Wind',p:'oo-peh-poh',ic:'💨'},
{l:'Jua',e:'Sun',p:'joo-ah',ic:'☀️'},
{l:'Mwezi',e:'Moon',p:'mweh-zee',ic:'🌙'},
{l:'Nyuki',e:'Bee',p:'n-yoo-kee',ic:'🐝'},
{l:'Samaki',e:'Fish',p:'sah-mah-kee',ic:'🐟'},
{l:'Mto',e:'River',p:'m-toh',ic:'🏞️'},
{l:'Mlima',e:'Mountain',p:'m-lee-mah',ic:'⛰️'},
{l:'Wingu',e:'Cloud',p:'ween-goo',ic:'☁️'},
{l:'Sungura',e:'Rabbit',p:'soon-goo-rah',ic:'🐇'},
{l:'Joto',e:'Heat / Hot weather',p:'joh-toh',ic:'🌡️'},
{l:'Baridi',e:'Cold',p:'bah-ree-dee',ic:'🥶'},
{l:'Ardhi',e:'Land / Earth / Ground',p:'ahr-dee',ic:'🌍'},
{l:'Bahari',e:'Sea / Ocean',p:'bah-hah-ree',ic:'🌊'},
{l:'Nyota',e:'Star',p:'n-yoh-tah',ic:'⭐'},
{l:'Mbingu',e:'Sky / Heaven',p:'m-been-goo',ic:'🌌'},
{l:'Mmea',e:'Plant',p:'m-meh-ah',ic:'🌱'},
{l:'Chanzo',e:'Spring / Source (water)',p:'chahn-zoh',ic:'💧'},
{l:'Mchanga',e:'Sand',p:'m-chahn-gah',ic:'🏖️'},
{l:'Tunda',e:'Fruit',p:'toon-dah',ic:'🍎'},
{l:'Maua',e:'Flowers',p:'mah-oo-ah',ic:'🌸'},
{l:'Majani',e:'Leaves / Grass',p:'mah-jah-nee',ic:'🌿'},
{l:'Kipepeo',e:'Butterfly',p:'kee-peh-peh-oh',ic:'🦋'},
{l:'Nzi',e:'Fly (insect)',p:'n-zee',ic:'🪰'},
{l:'Mchwa',e:'Termite / Ant',p:'m-chwah',ic:'🐜'},
{l:'Pwani',e:'Coast / Beach',p:'pwah-nee',ic:'🏖️'}
],
numbers:[
{l:'Moja',e:'One',p:'moh-jah',ic:'1️⃣'},
{l:'Mbili',e:'Two',p:'m-bee-lee',ic:'2️⃣'},
{l:'Tatu',e:'Three',p:'tah-too',ic:'3️⃣'},
{l:'Nne',e:'Four',p:'n-neh',ic:'4️⃣'},
{l:'Tano',e:'Five',p:'tah-noh',ic:'5️⃣'},
{l:'Sita',e:'Six',p:'see-tah',ic:'6️⃣'},
{l:'Saba',e:'Seven',p:'sah-bah',ic:'7️⃣'},
{l:'Nane',e:'Eight',p:'nah-neh',ic:'8️⃣'},
{l:'Tisa',e:'Nine',p:'tee-sah',ic:'9️⃣'},
{l:'Kumi',e:'Ten',p:'koo-mee',ic:'🔟'},
{l:'Kumi na moja',e:'Eleven',p:'koo-mee nah moh-jah',ic:'1️⃣'},
{l:'Ishirini',e:'Twenty',p:'ee-shee-ree-nee',ic:'✌️'},
{l:'Thelathini',e:'Thirty',p:'theh-lah-thee-nee',ic:'3️⃣'},
{l:'Arobaini',e:'Forty',p:'ah-roh-bah-ee-nee',ic:'4️⃣'},
{l:'Hamsini',e:'Fifty',p:'hahm-see-nee',ic:'5️⃣'},
{l:'Mia',e:'One hundred',p:'mee-ah',ic:'💯'},
{l:'Elfu',e:'One thousand',p:'ehl-foo',ic:'🔢'},
{l:'Saa',e:'Hour / Clock / Watch',p:'sah',ic:'⏰'},
{l:'Dakika',e:'Minute',p:'dah-kee-kah',ic:'⏱️'},
{l:'Sekunde',e:'Second',p:'seh-koon-deh',ic:'⏱️'},
{l:'Siku',e:'Day',p:'see-koo',ic:'📅'},
{l:'Wiki',e:'Week',p:'wee-kee',ic:'📆'},
{l:'Mwezi',e:'Month / Moon',p:'mweh-zee',ic:'📅'},
{l:'Mwaka',e:'Year',p:'mwah-kah',ic:'🎆'},
{l:'Leo',e:'Today',p:'leh-oh',ic:'📆'},
{l:'Kesho',e:'Tomorrow',p:'keh-shoh',ic:'➡️'},
{l:'Jana',e:'Yesterday',p:'jah-nah',ic:'⬅️'},
{l:'Usiku',e:'Night',p:'oo-see-koo',ic:'🌙'},
{l:'Asubuhi',e:'Morning',p:'ah-soo-boo-hee',ic:'🌅'},
{l:'Mchana',e:'Afternoon / Midday',p:'m-chah-nah',ic:'☀️'},
{l:'Jioni',e:'Evening',p:'jee-oh-nee',ic:'🌆'},
{l:'Juzi',e:'Day before yesterday',p:'joo-zee',ic:'⏮️'},
{l:'Kesho kutwa',e:'Day after tomorrow',p:'keh-shoh koot-wah',ic:'⏭️'},
{l:'Siku ya kuzaliwa',e:'Birthday',p:'see-koo yah koo-zah-lee-wah',ic:'🎂'},
{l:'Jumapili',e:'Sunday',p:'joo-mah-pee-lee',ic:'📅'},
{l:'Jumatatu',e:'Monday',p:'joo-mah-tah-too',ic:'📅'},
{l:'Jumanne',e:'Tuesday',p:'joo-mah-n-neh',ic:'📅'},
{l:'Jumatano',e:'Wednesday',p:'joo-mah-tah-noh',ic:'📅'},
{l:'Alhamisi',e:'Thursday',p:'ahl-hah-mee-see',ic:'📅'},
{l:'Ijumaa',e:'Friday',p:'ee-joo-mah',ic:'📅'}
],
verbs:[
{l:'Kwenda',e:'To go',p:'kwehn-dah',ic:'🚶'},
{l:'Kuja',e:'To come',p:'koo-jah',ic:'🏃'},
{l:'Kufika',e:'To arrive',p:'koo-fee-kah',ic:'🏁'},
{l:'Kula',e:'To eat',p:'koo-lah',ic:'🍽️'},
{l:'Kunywa',e:'To drink',p:'koon-ywah',ic:'🥤'},
{l:'Kulala',e:'To sleep',p:'koo-lah-lah',ic:'😴'},
{l:'Kukimbia',e:'To run',p:'koo-keem-bee-ah',ic:'🏃'},
{l:'Kusoma',e:'To read / study',p:'koo-soh-mah',ic:'📖'},
{l:'Kununua',e:'To buy',p:'koo-noo-noo-ah',ic:'🛒'},
{l:'Kutoa',e:'To give / offer',p:'koo-toh-ah',ic:'🎁'},
{l:'Kufanya',e:'To do / make',p:'koo-fah-nyah',ic:'⚒️'},
{l:'Kusema',e:'To speak / say',p:'koo-seh-mah',ic:'🗣️'},
{l:'Kuona',e:'To see',p:'koo-oh-nah',ic:'👁️'},
{l:'Kusikia',e:'To hear / feel',p:'koo-see-kee-ah',ic:'👂'},
{l:'Kutembea',e:'To walk',p:'koo-tehm-beh-ah',ic:'🚶'},
{l:'Kupenda',e:'To love',p:'koo-pehn-dah',ic:'❤️'},
{l:'Kupika',e:'To cook',p:'koo-pee-kah',ic:'🍳'},
{l:'Kuosha',e:'To wash',p:'koo-oh-shah',ic:'🚿'},
{l:'Kucheza',e:'To dance / play',p:'koo-cheh-zah',ic:'💃'},
{l:'Kuimba',e:'To sing',p:'koo-eem-bah',ic:'🎵'},
{l:'Kucheka',e:'To laugh',p:'koo-cheh-kah',ic:'😂'},
{l:'Kuanza',e:'To begin / start',p:'koo-ahn-zah',ic:'▶️'},
{l:'Kumaliza',e:'To finish',p:'koo-mah-lee-zah',ic:'✅'},
{l:'Kusaidia',e:'To help',p:'koo-sah-ee-dee-ah',ic:'🤝'},
{l:'Kufikiri',e:'To think',p:'koo-fee-kee-ree',ic:'🤔'},
{l:'Kukumbuka',e:'To remember',p:'koo-koom-boo-kah',ic:'🧠'},
{l:'Kuogopa',e:'To fear',p:'koo-oh-goh-pah',ic:'😨'},
{l:'Kukaa',e:'To stay / sit',p:'koo-kah',ic:'🏠'},
{l:'Kutoka',e:'To exit / come from',p:'koo-toh-kah',ic:'🚪'},
{l:'Kuingia',e:'To enter',p:'koo-een-gee-ah',ic:'🚪'},
{l:'Kupata',e:'To get / find / receive',p:'koo-pah-tah',ic:'🤲'},
{l:'Kujenga',e:'To build',p:'koo-jehn-gah',ic:'🏗️'},
{l:'Kukubaliana',e:'To agree',p:'koo-koo-bah-lee-ah-nah',ic:'✅'},
{l:'Kulima',e:'To farm / cultivate',p:'koo-lee-mah',ic:'🌾'},
{l:'Kufundisha',e:'To teach',p:'koo-foon-dee-shah',ic:'👩‍🏫'},
{l:'Kujifunza',e:'To learn',p:'koo-jee-foon-zah',ic:'📚'},
{l:'Kulipa',e:'To pay',p:'koo-lee-pah',ic:'💸'},
{l:'Kuuza',e:'To sell',p:'koo-oo-zah',ic:'🏪'},
{l:'Kuimba',e:'To sing',p:'koo-eem-bah',ic:'🎵'},
{l:'Kuandika',e:'To write',p:'koo-ahn-dee-kah',ic:'✍️'},
{l:'Kuelewa',e:'To understand',p:'koo-eh-leh-wah',ic:'💡'},
{l:'Kuchoka',e:'To be tired',p:'koo-choh-kah',ic:'😴'},
{l:'Kushangaa',e:'To be surprised',p:'koo-shahn-gah',ic:'😮'},
{l:'Kukasirika',e:'To be angry',p:'koo-kah-see-ree-kah',ic:'😠'},
{l:'Kufurahi',e:'To be happy',p:'koo-foo-rah-hee',ic:'😊'},
{l:'Kusimama',e:'To stand',p:'koo-see-mah-mah',ic:'🧍'},
{l:'Kulala chini',e:'To lie down',p:'koo-lah-lah chee-nee',ic:'🛏️'},
{l:'Kuruka',e:'To jump / fly',p:'koo-roo-kah',ic:'🦅'},
{l:'Kubeba',e:'To carry',p:'koo-beh-bah',ic:'🏋️'},
{l:'Kuanguka',e:'To fall',p:'koo-ahn-goo-kah',ic:'⬇️'}
],
adjectives:[
{l:'Nzuri',e:'Good / Beautiful / Nice',p:'n-zoo-ree',ic:'✨'},
{l:'Mbaya',e:'Bad',p:'m-bah-yah',ic:'👎'},
{l:'Kubwa',e:'Big / Large',p:'koob-wah',ic:'🐘'},
{l:'Ndogo',e:'Small',p:'n-doh-goh',ic:'🐜'},
{l:'Polepole',e:'Slow / Slowly',p:'poh-leh-poh-leh',ic:'🐢'},
{l:'Haraka',e:'Fast / Quickly',p:'hah-rah-kah',ic:'⚡'},
{l:'Kweli',e:'True / Really',p:'kweh-lee',ic:'✅'},
{l:'Sana',e:'Very / A lot',p:'sah-nah',ic:'💯'},
{l:'Nyeusi',e:'Black',p:'n-yeh-oo-see',ic:'⬛'},
{l:'Nyeupe',e:'White',p:'n-yeh-oo-peh',ic:'⬜'},
{l:'Mpya',e:'New',p:'m-pyah',ic:'🆕'},
{l:'Zamani',e:'Old / Long ago',p:'zah-mah-nee',ic:'📜'},
{l:'Ngumu',e:'Hard / Difficult',p:'n-goo-moo',ic:'💎'},
{l:'Laini',e:'Soft / Smooth',p:'lah-ee-nee',ic:'🧸'},
{l:'Hodari',e:'Clever / Skilled',p:'hoh-dah-ree',ic:'🧠'},
{l:'Tajiri',e:'Rich / Wealthy',p:'tah-jee-ree',ic:'💰'},
{l:'Maskini',e:'Poor',p:'mahs-kee-nee',ic:'😔'},
{l:'Ukarimu',e:'Generosity',p:'oo-kah-ree-moo',ic:'🎁'},
{l:'Tamu',e:'Sweet / Delicious',p:'tah-moo',ic:'🍬'},
{l:'Vipi',e:'How / What\'s up',p:'vee-pee',ic:'🤔'},
{l:'Rahisi',e:'Easy / Cheap',p:'rah-hee-see',ic:'😊'},
{l:'Ghali',e:'Expensive',p:'gah-lee',ic:'💎'},
{l:'Mzuri',e:'Good / Fine (person)',p:'m-zoo-ree',ic:'😊'},
{l:'Mrefu',e:'Tall / Long',p:'m-reh-foo',ic:'🦒'},
{l:'Mfupi',e:'Short',p:'m-foo-pee',ic:'🐛'},
{l:'Mzito',e:'Heavy',p:'m-zee-toh',ic:'⚖️'},
{l:'Mwepesi',e:'Light / Fast',p:'mweh-peh-see',ic:'🪶'},
{l:'Safi',e:'Clean',p:'sah-fee',ic:'✨'},
{l:'Chafu',e:'Dirty',p:'chah-foo',ic:'🤢'},
{l:'Nyingi',e:'Many / Much',p:'n-yeen-gee',ic:'🌐'},
{l:'Chache',e:'Few / Little',p:'chah-cheh',ic:'🤏'},
{l:'Wote',e:'All / Everyone',p:'woh-teh',ic:'👥'},
{l:'Kila',e:'Every / Each',p:'kee-lah',ic:'🔄'},
{l:'Mwema',e:'Kind / Good (person)',p:'mweh-mah',ic:'💚'},
{l:'Mkali',e:'Strict / Sharp',p:'m-kah-lee',ic:'😤'},
{l:'Jasiri',e:'Brave / Courageous',p:'jah-see-ree',ic:'💪'},
{l:'Mvivu',e:'Lazy',p:'m-vee-voo',ic:'😴'},
{l:'Amani',e:'Peace / Peaceful',p:'ah-mah-nee',ic:'🕊️'},
{l:'Furaha',e:'Happy / Joy',p:'foo-rah-hah',ic:'😊'}
],
places:[
{l:'Nairobi',e:'Capital of Kenya',p:'nah-ee-roh-bee',ic:'🏙️'},
{l:'Dar es Salaam',e:'Major city of Tanzania',p:'dahr ehs sah-lahm',ic:'🏙️'},
{l:'Kenya',e:'Kenya',p:'keh-nyah',ic:'🇰🇪'},
{l:'Tanzania',e:'Tanzania',p:'tahn-zah-nee-ah',ic:'🇹🇿'},
{l:'Hospitali',e:'Hospital',p:'hoh-spee-tah-lee',ic:'🏥'},
{l:'Shule',e:'School',p:'shoo-leh',ic:'🏫'},
{l:'Kanisa',e:'Church',p:'kah-nee-sah',ic:'⛪'},
{l:'Msikiti',e:'Mosque',p:'m-see-kee-tee',ic:'🕌'},
{l:'Soko',e:'Market',p:'soh-koh',ic:'🛒'},
{l:'Ziwa',e:'Lake',p:'zee-wah',ic:'🌊'},
{l:'Mlima',e:'Mountain',p:'m-lee-mah',ic:'⛰️'},
{l:'Barabara',e:'Road / Street',p:'bah-rah-bah-rah',ic:'🛣️'},
{l:'Mji',e:'Town / City',p:'m-jee',ic:'🏙️'},
{l:'Kijiji',e:'Village',p:'kee-jee-jee',ic:'🏡'},
{l:'Nchi',e:'Country',p:'n-chee',ic:'🌍'},
{l:'Ikulu',e:'Presidential palace',p:'ee-koo-loo',ic:'🏛️'},
{l:'Boda boda',e:'Motorcycle taxi',p:'boh-dah boh-dah',ic:'🛵'},
{l:'Daladala',e:'Minibus / Matatu',p:'dah-lah-dah-lah',ic:'🚌'},
{l:'Uwanja wa ndege',e:'Airport',p:'oo-wahn-jah wah n-deh-geh',ic:'✈️'},
{l:'Bandari',e:'Port / Harbour',p:'bahn-dah-ree',ic:'⚓'},
{l:'Pwani',e:'Coast / Beach',p:'pwah-nee',ic:'🏖️'},
{l:'Kisiwa',e:'Island',p:'kee-see-wah',ic:'🏝️'},
{l:'Daraja',e:'Bridge',p:'dah-rah-jah',ic:'🌉'},
{l:'Stendi',e:'Bus station',p:'stehn-dee',ic:'🚉'},
{l:'Uganda',e:'Uganda',p:'oo-gahn-dah',ic:'🇺🇬'},
{l:'Rwanda',e:'Rwanda',p:'rwahn-dah',ic:'🇷🇼'},
{l:'Mombasa',e:'Coastal city of Kenya',p:'mohm-bah-sah',ic:'🌊'},
{l:'Zanzibar',e:'Island of Tanzania',p:'zahn-zee-bahr',ic:'🏝️'},
{l:'Kilimanjaro',e:'Highest mountain in Africa',p:'kee-lee-mahn-jah-roh',ic:'⛰️'},
{l:'Serengeti',e:'Famous wildlife park',p:'seh-rehn-geh-tee',ic:'🦁'},
{l:'Hospitali ya serikali',e:'Government hospital',p:'hoh-spee-tah-lee yah seh-ree-kah-lee',ic:'🏥'},
{l:'Chuo kikuu',e:'University',p:'choo-oh kee-koo',ic:'🎓'},
{l:'Ofisi',e:'Office',p:'oh-fee-see',ic:'🏢'},
{l:'Hoteli',e:'Hotel',p:'hoh-teh-lee',ic:'🏨'},
{l:'Duka',e:'Shop / Store',p:'doo-kah',ic:'🏪'},
{l:'Benki',e:'Bank',p:'behn-kee',ic:'🏦'},
{l:'Posta',e:'Post office',p:'poh-stah',ic:'📮'},
{l:'Gereza',e:'Prison',p:'geh-reh-zah',ic:'🔒'},
{l:'Uwanja',e:'Field / Yard / Stadium',p:'oo-wahn-jah',ic:'🏟️'}
],
culture:[
{l:'Utamaduni',e:'Culture / Tradition',p:'oo-tah-mah-doo-nee',ic:'🎭'},
{l:'Harusi',e:'Wedding',p:'hah-roo-see',ic:'💒'},
{l:'Mazishi',e:'Funeral',p:'mah-zee-shee',ic:'🕊️'},
{l:'Mshairi',e:'Poet',p:'m-shah-ee-ree',ic:'📜'},
{l:'Shairi',e:'Poem',p:'shah-ee-ree',ic:'📝'},
{l:'Ngoma',e:'Drum / Traditional dance',p:'n-goh-mah',ic:'🥁'},
{l:'Taarab',e:'Traditional coastal music',p:'tah-rahb',ic:'🎶'},
{l:'Kanga',e:'Traditional wrap cloth',p:'kahn-gah',ic:'🧣'},
{l:'Kikoi',e:'Traditional coastal cloth',p:'kee-koy',ic:'🧣'},
{l:'Ujamaa',e:'African socialism / Brotherhood',p:'oo-jah-mah',ic:'🤝'},
{l:'Uhuru',e:'Freedom / Independence',p:'oo-hoo-roo',ic:'🕊️'},
{l:'Ubuntu',e:'Humanity / Togetherness',p:'oo-boon-too',ic:'❤️'},
{l:'Mila',e:'Custom / Tradition',p:'mee-lah',ic:'🎭'},
{l:'Desturi',e:'Custom / Habit',p:'deh-stoo-ree',ic:'🏛️'},
{l:'Mazungumzo',e:'Conversation / Discussion',p:'mah-zoon-goom-zoh',ic:'💬'},
{l:'Hadithi',e:'Story / Tale',p:'hah-dee-thee',ic:'📖'},
{l:'Methali',e:'Proverb',p:'meh-thah-lee',ic:'💡'},
{l:'Mchezo',e:'Game / Play / Sport',p:'m-cheh-zoh',ic:'⚽'},
{l:'Muziki',e:'Music',p:'moo-zee-kee',ic:'🎵'},
{l:'Sanaa',e:'Art',p:'sah-nah',ic:'🎨'},
{l:'Dini',e:'Religion',p:'dee-nee',ic:'🙏'},
{l:'Msikiti',e:'Mosque',p:'m-see-kee-tee',ic:'🕌'},
{l:'Sala',e:'Prayer',p:'sah-lah',ic:'🙏'},
{l:'Ramadani',e:'Ramadan',p:'rah-mah-dah-nee',ic:'🌙'},
{l:'Eid',e:'Eid celebration',p:'eed',ic:'🎉'},
{l:'Mazingira',e:'Environment / Surroundings',p:'mah-zeen-gee-rah',ic:'🌍'},
{l:'Heshima',e:'Respect / Honor',p:'heh-shee-mah',ic:'🎖️'},
{l:'Ukweli',e:'Truth',p:'oo-kweh-lee',ic:'💯'},
{l:'Amani',e:'Peace',p:'ah-mah-nee',ic:'🕊️'},
{l:'Imani',e:'Faith / Trust',p:'ee-mah-nee',ic:'🙏'},
{l:'Starehe',e:'Comfort / Leisure',p:'stah-reh-heh',ic:'😊'},
{l:'Sherehe',e:'Celebration / Party',p:'sheh-reh-heh',ic:'🎉'},
{l:'Mwanzo',e:'Beginning',p:'mwahn-zoh',ic:'▶️'},
{l:'Mwisho',e:'End',p:'mwee-shoh',ic:'🏁'},
{l:'Historia',e:'History',p:'hee-stoh-ree-ah',ic:'📜'},
{l:'Lugha',e:'Language',p:'loo-gah',ic:'🗣️'},
{l:'Kiswahili',e:'The Swahili language',p:'kee-swah-hee-lee',ic:'🌍'},
{l:'Afrika',e:'Africa',p:'ah-free-kah',ic:'🌍'},
{l:'Uhusiano',e:'Relationship',p:'oo-hoo-see-ah-noh',ic:'🤝'}
],
wildlife:[
{l:'Twiga',e:'Giraffe',p:'twee-gah',ic:'🦒'},
{l:'Kiboko',e:'Hippo',p:'kee-boh-koh',ic:'🦛'},
{l:'Faru',e:'Rhinoceros',p:'fah-roo',ic:'🦏'},
{l:'Chui',e:'Leopard',p:'choo-ee',ic:'🐆'},
{l:'Duma',e:'Cheetah',p:'doo-mah',ic:'🐆'},
{l:'Nyati',e:'Buffalo',p:'n-yah-tee',ic:'🐃'},
{l:'Swala',e:'Gazelle / Antelope',p:'swah-lah',ic:'🦌'},
{l:'Pundamilia',e:'Zebra',p:'poon-dah-mee-lee-ah',ic:'🦓'},
{l:'Sokwe',e:'Chimpanzee',p:'sohk-weh',ic:'🐒'},
{l:'Gorila',e:'Gorilla',p:'goh-ree-lah',ic:'🦍'},
{l:'Nguruwe',e:'Warthog / Pig',p:'n-goo-roo-weh',ic:'🐗'},
{l:'Mbuni',e:'Ostrich',p:'m-boo-nee',ic:'🦜'},
{l:'Tai',e:'Eagle',p:'tah-ee',ic:'🦅'},
{l:'Korongo',e:'Flamingo',p:'koh-rohn-goh',ic:'🦩'},
{l:'Mamba',e:'Crocodile',p:'mahm-bah',ic:'🐊'},
{l:'Nyoka',e:'Snake',p:'n-yoh-kah',ic:'🐍'},
{l:'Kobe',e:'Tortoise',p:'koh-beh',ic:'🐢'},
{l:'Nzige',e:'Locust',p:'n-zee-geh',ic:'🦗'},
{l:'Perege',e:'Wildebeest / Gnu',p:'peh-reh-geh',ic:'🐃'},
{l:'Paa',e:'Antelope (small)',p:'pah',ic:'🦌'},
{l:'Mbogo',e:'Cape buffalo',p:'m-boh-goh',ic:'🐂'},
{l:'Ngo',e:'Leopard',p:'ngoh',ic:'🐆'},
{l:'Bundi',e:'Owl',p:'boon-dee',ic:'🦉'},
{l:'Kipanga',e:'Kite bird / Falcon',p:'kee-pahn-gah',ic:'🦅'},
{l:'Papara',e:'Hyena (slang)',p:'pah-pah-rah',ic:'🐺'},
{l:'Fisi',e:'Hyena',p:'fee-see',ic:'🐺'},
{l:'Kinyonga',e:'Chameleon',p:'keen-yohn-gah',ic:'🦎'},
{l:'Mjusi',e:'Lizard',p:'m-joo-see',ic:'🦎'},
{l:'Samaki wa bahari',e:'Sea fish',p:'sah-mah-kee wah bah-hah-ree',ic:'🐠'},
{l:'Nyangumi',e:'Whale',p:'n-yahn-goo-mee',ic:'🐋'},
{l:'Pomboo',e:'Dolphin',p:'pohm-boh',ic:'🐬'},
{l:'Pweza',e:'Octopus',p:'pweh-zah',ic:'🐙'},
{l:'Kaa',e:'Crab',p:'kah',ic:'🦀'},
{l:'Hifadhi ya wanyama',e:'Wildlife reserve',p:'hee-fah-dee yah wah-n-yah-mah',ic:'🌿'},
{l:'Wanyama',e:'Animals',p:'wah-n-yah-mah',ic:'🐘'},
{l:'Mbio za mbio',e:'Migration',p:'m-bee-oh zah m-bee-oh',ic:'🚶'},
{l:'Uwindaji',e:'Hunting',p:'oo-ween-dah-jee',ic:'🏹'},
{l:'Hifadhi',e:'Conservation / Reserve',p:'hee-fah-dee',ic:'🛡️'},
{l:'Tembo wa Afrika',e:'African elephant',p:'tehm-boh wah ah-free-kah',ic:'🐘'}
],
coast:[
{l:'Bahari',e:'Sea / Ocean',p:'bah-hah-ree',ic:'🌊'},
{l:'Pwani',e:'Coast / Beach',p:'pwah-nee',ic:'🏖️'},
{l:'Kisiwa',e:'Island',p:'kee-see-wah',ic:'🏝️'},
{l:'Meli',e:'Ship / Large boat',p:'meh-lee',ic:'🚢'},
{l:'Mashua',e:'Small boat / Dhow',p:'mah-shoo-ah',ic:'⛵'},
{l:'Jahazi',e:'Traditional dhow',p:'jah-hah-zee',ic:'⛵'},
{l:'Samaki',e:'Fish',p:'sah-mah-kee',ic:'🐟'},
{l:'Mvuvi',e:'Fisherman',p:'m-voo-vee',ic:'🎣'},
{l:'Wavuvi',e:'Fishermen',p:'wah-voo-vee',ic:'🎣'},
{l:'Matumbawe',e:'Coral reef',p:'mah-toom-bah-weh',ic:'🪸'},
{l:'Mchanga',e:'Sand',p:'m-chahn-gah',ic:'🏖️'},
{l:'Mawimbi',e:'Waves',p:'mah-weem-bee',ic:'🌊'},
{l:'Upepo wa bahari',e:'Sea breeze',p:'oo-peh-poh wah bah-hah-ree',ic:'💨'},
{l:'Bandari',e:'Port / Harbour',p:'bahn-dah-ree',ic:'⚓'},
{l:'Zanzibar',e:'Zanzibar island',p:'zahn-zee-bahr',ic:'🏝️'},
{l:'Lamu',e:'Lamu island (Kenya)',p:'lah-moo',ic:'🏛️'},
{l:'Mombasa',e:'Coastal city Kenya',p:'mohm-bah-sah',ic:'🌊'},
{l:'Dar es Salaam',e:'Coastal city Tanzania',p:'dahr ehs sah-lahm',ic:'🏙️'},
{l:'Pilipili hoho',e:'Bell pepper',p:'pee-lee-pee-lee hoh-hoh',ic:'🫑'},
{l:'Nazi',e:'Coconut',p:'nah-zee',ic:'🥥'},
{l:'Maji ya nazi',e:'Coconut water',p:'mah-jee yah nah-zee',ic:'🥥'},
{l:'Mkate wa ufuta',e:'Sesame flatbread',p:'m-kah-teh wah oo-foo-tah',ic:'🫓'},
{l:'Urojo',e:'Zanzibar mix / Coconut soup',p:'oo-roh-joh',ic:'🍲'},
{l:'Nyama choma',e:'Grilled meat',p:'n-yah-mah choh-mah',ic:'🍖'},
{l:'Ugua wa bahari',e:'Seasickness',p:'oo-goo-ah wah bah-hah-ree',ic:'🤢'},
{l:'Dau',e:'Traditional small dhow',p:'dah-oo',ic:'⛵'},
{l:'Makuti',e:'Palm leaf thatch',p:'mah-koo-tee',ic:'🌴'},
{l:'Mnazi',e:'Coconut palm tree',p:'m-nah-zee',ic:'🌴'},
{l:'Mwambao',e:'Coastline',p:'mwahm-bah-oh',ic:'🏖️'},
{l:'Biashara',e:'Trade / Business',p:'bee-ah-shah-rah',ic:'💼'},
{l:'Kipande',e:'Piece / Fragment / Coin',p:'kee-pahn-deh',ic:'🪙'},
{l:'Historia ya Waswahili',e:'Swahili people\'s history',p:'hee-stoh-ree-ah yah wah-swah-hee-lee',ic:'📜'},
{l:'Waswahili',e:'Swahili people',p:'wah-swah-hee-lee',ic:'🌍'},
{l:'Usanifu wa Kiarabu',e:'Arabic architecture',p:'oo-sah-nee-foo wah kee-ah-rah-boo',ic:'🏛️'},
{l:'Mlango Mkubwa',e:'Fort Jesus gate',p:'m-lahn-goh m-koob-wah',ic:'🏰'},
{l:'Uchumi wa bahari',e:'Maritime economy',p:'oo-choo-mee wah bah-hah-ree',ic:'💰'},
{l:'Uvuvi',e:'Fishing (activity)',p:'oo-voo-vee',ic:'🎣'},
{l:'Usafiri wa baharini',e:'Sea travel',p:'oo-sah-fee-ree wah bah-hah-ree-nee',ic:'🚢'},
{l:'Mangrove',e:'Mangrove forest',p:'mahn-grohv',ic:'🌿'}
]
};
